kind: pipeline
name: arm64-quicktests

platform:
  os: linux
  arch: arm64

steps:
- name: quicktests
  image: gcc:8
  commands: [ make quicktests ]
---
kind: pipeline
name: arm64-checkperf

platform:
  os: linux
  arch: arm64

steps:
- name: checkperf
  image: gcc:8
  environment:
    CHECKPERF_REPOSITORY: https://github.com/lemire/simdjson
  commands: [ make checkperf ]
---
kind: pipeline
name: arm64-build

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: gcc:8
  commands: [ make, make amalgamate ]
# ---
# kind: pipeline
# name: arm64-slowtests

# platform:
#   os: linux
#   arch: arm64

# steps:
# - name: slowtests
#   image: gcc:8
#   commands: [ make slowtests ]
